version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build__workflow:
    jobs:
      - build
